services:
  web:
    image: wmap/apache:latest
    build: 
      context: .
      dockerfile: .docker/apache.dockerfile
    ports:
      - "80" 
    environment:
      TERM: xterm-color
      PORT: 80
    networks:
      - webnet

networks:
  webnet:
